In [1]:
import pandas as pd
import numpy as np
import requests
import time
import mygene
import myvariant

from Bio import Entrez, SeqIO
from Bio.Seq import Seq

In [2]:
df = pd.read_csv("datosGene4PD/t_common_variant.txt", sep = "\t", index_col = False)

In [3]:
df

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Unnamed: 10
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,NaN
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,NaN
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,NaN
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1053,rs117896735,INPP5F,13,U,13,U,1.21E-11,1.77,-,29700661,NaN
1054,rs12456492,RIT2,21,U,21,U,2.15E-11,1.1,-,29700661,NaN
1055,rs7155501,GCH1,15,U,15,U,1.25E-10,1.12,-,29700661,NaN
1056,rs10797576,SIPA1L2,21,U,21,U,1.76E-10,1.13,-,29700661,NaN
1057,rs62120679,TMPRSS9,13,U,13,U,2.52E-09,1.14,-,29700661,NaN

In [4]:
df_filtrado = df[df["SNPs_symbol"].str.startswith('rs')].reset_index(drop = True)

In [5]:
df_filtrado = df_filtrado.drop(["Unnamed: 10"], axis = 1)

In [6]:
df_filtrado = df_filtrado.dropna(subset = ['gene_symbol']).reset_index(drop = True)

In [42]:
mv = myvariant.MyVariantInfo()

In [43]:
prueba = mv.querymany(['rs757765789'], scopes = "dbsnp.rsid", fields = "dbsnp", species = "human")

In [47]:
prueba2 = mv.getvariant('rs202015799', fields = "dbsnp,gwascatalog,clinvar")

In [27]:
prueba[0]["dbsnp"]["gene"]["strand"]

'+'

In [7]:
def busca_rsIDs_cadena(df):
    
    lista_rsids = df["SNPs_symbol"].unique().tolist()

    mv = myvariant.MyVariantInfo()

    resultados = mv.querymany(lista_rsids, scopes = "dbsnp.rsid", fields = "dbsnp", species = "human")

    diccionario_snps = {}

    cromosomas_validos = [str(i) for i in range(1, 23)] + ["X", "Y", "MT"]

    bases_validas = ["A", "C", "G", "T", "a", "c", "g", "t"]

    cadenas_validas = ["+", "-", "1", "-1"]

    for resultado in resultados:
        rsid = resultado.get("query")

        if "notfound" in resultado:
            continue

        info_dbsnp = resultado.get("dbsnp", {})

        hg19 = info_dbsnp.get("hg19", {})

        if not hg19:
            continue

        if isinstance(hg19, list):
            hg19 = hg19[0]

        cromosoma = str(info_dbsnp.get("chrom"))
        if cromosoma not in cromosomas_validos:
            continue

        pos_hg19 = hg19.get("start")
    
        ef_allele = info_dbsnp.get("ref", '')
        alt_allele = info_dbsnp.get("alt", '')

        if ef_allele not in bases_validas or alt_allele not in bases_validas:
            continue

        gene_info = info_dbsnp.get("gene", {})
        gene_symbol = "inter"
        cadena = None

        if isinstance(gene_info, dict):
            gene_symbol = gene_info.get("symbol", "inter")
            cadena = gene_info.get("strand", None)

        elif isinstance(gene_info, list):
            gene_symbol = gene_info[0].get("symbol", "inter")
            cadena = gene_info[0].get("strand", None)

        if rsid not in diccionario_snps:

            diccionario_snps[rsid] = {"SNPs_symbol": rsid, "Chr_corr": cromosoma, "SNP_position_corr": pos_hg19, "Effect_allele_corr": ef_allele, "Alternate_allele_corr": [alt_allele], "Gene_symbol_corr": gene_symbol, "Cadena": cadena}

        else:

            if alt_allele not in diccionario_snps[rsid]["Alternate_allele_corr"]:
                diccionario_snps[rsid]["Alternate_allele_corr"].append(alt_allele)

    datos_corregidos = list(diccionario_snps.values())

    return pd.DataFrame(datos_corregidos)

In [8]:
df_corr = busca_rsIDs_cadena(df_filtrado)

474 input query terms found dup hits:	[('rs202015799', 2), ('rs1994090', 3), ('rs2708453', 2), ('rs4768212', 2), ('rs7304281', 2), ('rs204
1 input query terms found no hit:	['rs2740594c']

In [9]:
df_corr

,SNPs_symbol,Chr_corr,SNP_position_corr,Effect_allele_corr,Alternate_allele_corr,Gene_symbol_corr,Cadena
0,rs757765789,6,142758601,T,[G],ADGRG6,+
1,rs202015799,1,155839054,C,"[G, T]",SYT11,+
2,rs1994090,12,40428561,G,"[A, T, C]",SLC2A13,-
3,rs2708453,12,40478652,G,"[A, T]",SLC2A13,-
4,rs4768212,12,40474147,C,"[A, T]",SLC2A13,-
...,...,...,...,...,...,...,...
881,rs666463,17,76425480,A,[T],DNAH17,-
882,rs1941685,18,31304318,G,"[T, C]",ASXL3,+
883,rs8087969,18,48683589,T,"[G, A]",inter,None
884,rs77351827,20,6006041,C,[T],CRLS1,+
885,rs2248244,21,38852361,G,[A],DYRK1A,+

In [10]:
df_nuevo = pd.merge(df_filtrado, df_corr, on = "SNPs_symbol", how = "left")

In [11]:
df_nuevo

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Chr_corr,SNP_position_corr,Effect_allele_corr,Alternate_allele_corr,Gene_symbol_corr,Cadena
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,6,142758601.0,T,[G],ADGRG6,+
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,1,155839054.0,C,"[G, T]",SYT11,+
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,12,40428561.0,G,"[A, T, C]",SLC2A13,-
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,12,40478652.0,G,"[A, T]",SLC2A13,-
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,12,40474147.0,C,"[A, T]",SLC2A13,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,17,DNAH17,rs666463,76425480,A,T,2.90E-09,1.08,-,https://doi.org/10.1101/388165,17,76425480.0,A,[T],DNAH17,-
1010,18,ASXL3,rs1941685,31304318,T,G,1.61E-08,1.05,-,https://doi.org/10.1101/388165,18,31304318.0,G,"[T, C]",ASXL3,+
1011,18,MEX3C,rs8087969,48683589,T,G,1.46E-08,0.94,-,https://doi.org/10.1101/388165,18,48683589.0,T,"[G, A]",inter,None
1012,20,CRLS1,rs77351827,6006041,T,C,7.94E-09,1.08,-,https://doi.org/10.1101/388165,20,6006041.0,C,[T],CRLS1,+
1013,21,DYRK1A,rs2248244,38852361,A,G,2.51E-11,1.07,-,https://doi.org/10.1101/388165,21,38852361.0,G,[A],DYRK1A,+

In [12]:
df_nuevo = df_nuevo[["Chr", "SNPs_symbol", "SNP_position", "effect_allele", "alternate_allele", "joint_phase_OR", "Chr_corr", "SNP_position_corr", "Effect_allele_corr", "Alternate_allele_corr", "Cadena"]]

In [13]:
df_nuevo

,Chr,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_OR,Chr_corr,SNP_position_corr,Effect_allele_corr,Alternate_allele_corr,Cadena
0,6,rs757765789,142758601,T,G,1.06,6,142758601.0,T,[G],+
1,1,rs202015799,155839054,C,T,-,1,155839054.0,C,"[G, T]",+
2,12,rs1994090,40428561,G,T,12.05,12,40428561.0,G,"[A, T, C]",-
3,12,rs2708453,40478652,G,T,12.05,12,40478652.0,G,"[A, T]",-
4,12,rs4768212,40474147,C,T,12.05,12,40474147.0,C,"[A, T]",-
...,...,...,...,...,...,...,...,...,...,...,...
1009,17,rs666463,76425480,A,T,1.08,17,76425480.0,A,[T],-
1010,18,rs1941685,31304318,T,G,1.05,18,31304318.0,G,"[T, C]",+
1011,18,rs8087969,48683589,T,G,0.94,18,48683589.0,T,"[G, A]",None
1012,20,rs77351827,6006041,T,C,1.08,20,6006041.0,C,[T],+
1013,21,rs2248244,38852361,A,G,1.07,21,38852361.0,G,[A],+

In [14]:
df_puro = df_nuevo.dropna(subset = ["SNP_position_corr"]).reset_index(drop = True)
df_puro = df_puro.dropna(subset = ["Cadena"]).reset_index(drop = True)

In [15]:
df_puro

,Chr,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_OR,Chr_corr,SNP_position_corr,Effect_allele_corr,Alternate_allele_corr,Cadena
0,6,rs757765789,142758601,T,G,1.06,6,142758601.0,T,[G],+
1,1,rs202015799,155839054,C,T,-,1,155839054.0,C,"[G, T]",+
2,12,rs1994090,40428561,G,T,12.05,12,40428561.0,G,"[A, T, C]",-
3,12,rs2708453,40478652,G,T,12.05,12,40478652.0,G,"[A, T]",-
4,12,rs4768212,40474147,C,T,12.05,12,40474147.0,C,"[A, T]",-
...,...,...,...,...,...,...,...,...,...,...,...
770,17,rs61169879,59917366,T,C,1.09,17,59917366.0,C,"[A, T]",-
771,17,rs666463,76425480,A,T,1.08,17,76425480.0,A,[T],-
772,18,rs1941685,31304318,T,G,1.05,18,31304318.0,G,"[T, C]",+
773,20,rs77351827,6006041,T,C,1.08,20,6006041.0,C,[T],+
774,21,rs2248244,38852361,A,G,1.07,21,38852361.0,G,[A],+

In [16]:
df_puro["SNP_position_corr"] = df_puro["SNP_position_corr"].astype(int)

In [17]:
def valida_alelos_SNP(fila):

    effect_allele_original = fila["effect_allele"]
    alternate_allele_original = fila["alternate_allele"]
    effect_allele_rsID = fila["Effect_allele_corr"]
    alternate_allele_rsID = fila["Alternate_allele_corr"]

    alelos_original = [effect_allele_original, alternate_allele_original]
    alelos_rsID = [effect_allele_rsID] + alternate_allele_rsID

    if all(alelo in alelos_rsID for alelo in alelos_original):
        
        return "Coincide perfecto"

    complementario = {"A": "T", "T": "A", "C": "G", "G": "C"}
    alelos_original_complementario = [complementario.get(alelo, alelo) for alelo in alelos_original]

    if all(alelo in alelos_rsID for alelo in alelos_original_complementario):
        
        return "Coincide complementario"

    return "No coincide"

In [18]:
df_puro["Valida_alelos"] = df_puro.apply(valida_alelos_SNP, axis = 1)

In [19]:
print(df_puro["Valida_alelos"].value_counts())

Coincide perfecto          762
No coincide                 10
Coincide complementario      3
Name: Valida_alelos, dtype: int64

In [20]:
df_puro = df_puro[df_puro["Valida_alelos"] != "No coincide"].reset_index(drop = True)

In [21]:
complementario = {"A": "T", "T": "A", "C": "G", "G": "C"}

In [22]:
filas_comp = df_puro["Valida_alelos"] == "Coincide complementario"
df_puro.loc[filas_comp, "effect_allele"] = df_puro.loc[filas_comp, "effect_allele"].map(complementario)
df_puro.loc[filas_comp, "alternate_allele"] = df_puro.loc[filas_comp, "alternate_allele"].map(complementario)

In [23]:
df_puro

,Chr,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_OR,Chr_corr,SNP_position_corr,Effect_allele_corr,Alternate_allele_corr,Cadena,Valida_alelos
0,6,rs757765789,142758601,T,G,1.06,6,142758601,T,[G],+,Coincide perfecto
1,1,rs202015799,155839054,C,T,-,1,155839054,C,"[G, T]",+,Coincide perfecto
2,12,rs1994090,40428561,G,T,12.05,12,40428561,G,"[A, T, C]",-,Coincide perfecto
3,12,rs2708453,40478652,G,T,12.05,12,40478652,G,"[A, T]",-,Coincide perfecto
4,12,rs4768212,40474147,C,T,12.05,12,40474147,C,"[A, T]",-,Coincide perfecto
...,...,...,...,...,...,...,...,...,...,...,...,...
760,17,rs61169879,59917366,T,C,1.09,17,59917366,C,"[A, T]",-,Coincide perfecto
761,17,rs666463,76425480,A,T,1.08,17,76425480,A,[T],-,Coincide perfecto
762,18,rs1941685,31304318,T,G,1.05,18,31304318,G,"[T, C]",+,Coincide perfecto
763,20,rs77351827,6006041,T,C,1.08,20,6006041,C,[T],+,Coincide perfecto
764,21,rs2248244,38852361,A,G,1.07,21,38852361,G,[A],+,Coincide perfecto

In [24]:
print(df_puro["Cadena"].value_counts(dropna = False))

+    403
-    362
Name: Cadena, dtype: int64

In [25]:
df_puro_OR = df_puro[~df_puro["joint_phase_OR"].isin(["-", "NA", "NaN"])]
df_puro_OR = df_puro_OR.dropna(subset = ["joint_phase_OR"]).reset_index(drop = True)

In [26]:
df_puro_OR

,Chr,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_OR,Chr_corr,SNP_position_corr,Effect_allele_corr,Alternate_allele_corr,Cadena,Valida_alelos
0,6,rs757765789,142758601,T,G,1.06,6,142758601,T,[G],+,Coincide perfecto
1,12,rs1994090,40428561,G,T,12.05,12,40428561,G,"[A, T, C]",-,Coincide perfecto
2,12,rs2708453,40478652,G,T,12.05,12,40478652,G,"[A, T]",-,Coincide perfecto
3,12,rs4768212,40474147,C,T,12.05,12,40474147,C,"[A, T]",-,Coincide perfecto
4,14,rs7304281,40465942,T,C,12.05,12,126945694,T,"[G, C]",+,Coincide perfecto
...,...,...,...,...,...,...,...,...,...,...,...,...
704,17,rs61169879,59917366,T,C,1.09,17,59917366,C,"[A, T]",-,Coincide perfecto
705,17,rs666463,76425480,A,T,1.08,17,76425480,A,[T],-,Coincide perfecto
706,18,rs1941685,31304318,T,G,1.05,18,31304318,G,"[T, C]",+,Coincide perfecto
707,20,rs77351827,6006041,T,C,1.08,20,6006041,C,[T],+,Coincide perfecto
708,21,rs2248244,38852361,A,G,1.07,21,38852361,G,[A],+,Coincide perfecto

In [27]:
archivo_genoma = "datosGene4PD/Homo_sapiens.GRCh37.completo.fa"

genoma = SeqIO.index(archivo_genoma, "fasta")

In [25]:
def extrae_region_sana(df_final_fila, ventana = 500):

    cromosoma = str(df_final_fila["Chr_corr"])
    pos_snp = df_final_fila["SNP_position_corr"]

    alelo_sano = df_final_fila["effect_allele"]

    secuencia_chr = genoma[cromosoma].seq

    id_snp_python = pos_snp - 1

    inicio = max(0, id_snp_python - ventana)
    fin = id_snp_python + ventana + 1

    molde_forward = str(secuencia_chr[inicio : fin]).upper()

    pos_relativa_snp = id_snp_python - inicio

    reg_sana_forward = molde_forward[:pos_relativa_snp] + alelo_sano + molde_forward[pos_relativa_snp + 1:]
    
    
    cadena = df_final_fila.get("Cadena")
    if cadena == 1 or cadena == "+":
        
        reg_sana = reg_sana_forward

    else:

        reg_sana = str(Seq(reg_sana_forward).reverse_complement())

    return reg_sana.lower()

In [26]:
def extrae_region_parkinson(df_final_fila, reg_sana, ventana = 500):
    
    cadena = df_final_fila.get("Cadena")
    pos_snp = df_final_fila["SNP_position_corr"]

    alelo_parkinson = df_final_fila["alternate_allele"]

    id_snp_python = pos_snp - 1
    inicio = max(0, id_snp_python - ventana)
    pos_relativa_snp = id_snp_python - inicio

    if cadena == 1 or cadena == "+":

        snp = pos_relativa_snp
        nuc = alelo_parkinson
    
    else:

        snp = len(reg_sana) - 1 - pos_relativa_snp
        nuc = str(Seq(alelo_parkinson).complement())

    nuc = nuc.lower()

    reg_park = reg_sana[:snp] + nuc + reg_sana[snp + 1:]

    return reg_park

In [32]:
secuencias = []
etiquetas = []
# rsIDs = []
for i in range(len(df_puro)):

    fila = df_puro.iloc[i]
        
    reg_sana = extrae_region_sana(fila)
    secuencias.append(str(reg_sana))
    etiquetas.append("Sano")
    # rsIDs.append(fila["SNPs_symbol"])
    
    reg_park = extrae_region_parkinson(fila, reg_sana)
    secuencias.append(str(reg_park))
    etiquetas.append("Riesgo_PD")
    # rsIDs.append(fila["SNPs_symbol"])

In [33]:
df_base_final = pd.DataFrame(list(zip(secuencias, etiquetas)), columns = ["Secuencia", "Etiqueta"])

In [34]:
df_base_final

                                              Secuencia   Etiqueta
0     atatactatgaatataactataatatacatatgtaaaatagctcag...       Sano
1     atatactatgaatataactataatatacatatgtaaaatagctcag...  Riesgo_PD
2     ccagggacatcatcaaaaggaatatccaggtgagtaggaagtgtgt...       Sano
3     ccagggacatcatcaaaaggaatatccaggtgagtaggaagtgtgt...  Riesgo_PD
4     atgttatcatgtaaatatctagttattgatcaataacgatgaccat...       Sano
...                                                 ...        ...
1525  caccagccaccctgatcagtcagcagccatcaacatccatgcaaga...  Riesgo_PD
1526  agtctcttccattccttgaaggcacagagaggtgaagaagttgcag...       Sano
1527  agtctcttccattccttgaaggcacagagaggtgaagaagttgcag...  Riesgo_PD
1528  ttttttactagtcttagaaacagtgttggtgttttgtttttgtttt...       Sano
1529  ttttttactagtcttagaaacagtgttggtgttttgtttttgtttt...  Riesgo_PD

[1530 rows x 2 columns]

In [43]:
df_base_final.to_csv('datosGene4PD/base_flanqueantes_1530.csv', index = False)

In [28]:
def extrae_region_sana_OR(df_final_fila, ventana = 500):

    cromosoma = str(df_final_fila["Chr_corr"])
    pos_snp = df_final_fila["SNP_position_corr"]

    if float(df_final_fila["joint_phase_OR"]) <= 1:
        alelo_sano = df_final_fila["effect_allele"]

    else:
        alelo_sano = df_final_fila["alternate_allele"]

    secuencia_chr = genoma[cromosoma].seq

    id_snp_python = pos_snp - 1

    inicio = max(0, id_snp_python - ventana)
    fin = id_snp_python + ventana + 1

    molde_forward = str(secuencia_chr[inicio : fin]).upper()

    pos_relativa_snp = id_snp_python - inicio

    reg_sana_forward = molde_forward[:pos_relativa_snp] + alelo_sano + molde_forward[pos_relativa_snp + 1:]
    
    
    cadena = df_final_fila.get("Cadena")
    if cadena == 1 or cadena == "+":
        
        reg_sana = reg_sana_forward

    else:

        reg_sana = str(Seq(reg_sana_forward).reverse_complement())

    return reg_sana.lower()

In [29]:
def extrae_region_parkinson_OR(df_final_fila, reg_sana, ventana = 500):
    
    cadena = df_final_fila.get("Cadena")
    pos_snp = df_final_fila["SNP_position_corr"]

    if float(df_final_fila["joint_phase_OR"]) <= 1:

        alelo_parkinson = df_final_fila["alternate_allele"]

    else:
        
        alelo_parkinson = df_final_fila["effect_allele"]
        

    id_snp_python = pos_snp - 1
    inicio = max(0, id_snp_python - ventana)
    pos_relativa_snp = id_snp_python - inicio

    if cadena == 1 or cadena == "+":

        snp = pos_relativa_snp
        nuc = alelo_parkinson
    
    else:

        snp = len(reg_sana) - 1 - pos_relativa_snp
        nuc = str(Seq(alelo_parkinson).complement())

    nuc = nuc.lower()

    reg_park = reg_sana[:snp] + nuc + reg_sana[snp + 1:]

    return reg_park

In [64]:
secuencias = []
etiquetas = []
# rsIDs = []
for i in range(len(df_puro_OR)):

    fila = df_puro_OR.iloc[i]
        
    reg_sana = extrae_region_sana_OR(fila)
    secuencias.append(str(reg_sana))
    etiquetas.append("Sano")
    # rsIDs.append(fila["SNPs_symbol"])
    
    reg_park = extrae_region_parkinson_OR(fila, reg_sana)
    secuencias.append(str(reg_park))
    etiquetas.append("Riesgo_PD")
    # rsIDs.append(fila["SNPs_symbol"])

In [65]:
df_base_final_or = pd.DataFrame(list(zip(secuencias, etiquetas)), columns = ["Secuencia", "Etiqueta"])

In [66]:
df_base_final_or

                                              Secuencia   Etiqueta
0     atatactatgaatataactataatatacatatgtaaaatagctcag...       Sano
1     atatactatgaatataactataatatacatatgtaaaatagctcag...  Riesgo_PD
2     atgttatcatgtaaatatctagttattgatcaataacgatgaccat...       Sano
3     atgttatcatgtaaatatctagttattgatcaataacgatgaccat...  Riesgo_PD
4     ctttgaccaaccaactacttcaagttggagtttttacaacaccttt...       Sano
...                                                 ...        ...
1413  caccagccaccctgatcagtcagcagccatcaacatccatgcaaga...  Riesgo_PD
1414  agtctcttccattccttgaaggcacagagaggtgaagaagttgcag...       Sano
1415  agtctcttccattccttgaaggcacagagaggtgaagaagttgcag...  Riesgo_PD
1416  ttttttactagtcttagaaacagtgttggtgttttgtttttgtttt...       Sano
1417  ttttttactagtcttagaaacagtgttggtgttttgtttttgtttt...  Riesgo_PD

[1418 rows x 2 columns]

In [67]:
df_base_final_or.to_csv('datosGene4PD/base_flanqueantes_OR_1418.csv', index = False)

PRUEBO A REDUCIR TAMAÑO DE VENTANA A 20

In [31]:
secuencias = []
etiquetas = []
rsIDs = []
for i in range(len(df_puro_OR)):

    fila = df_puro_OR.iloc[i]
        
    reg_sana = extrae_region_sana_OR(fila, ventana = 20)
    secuencias.append(str(reg_sana))
    etiquetas.append("Sano")
    rsIDs.append(fila["SNPs_symbol"])
    
    reg_park = extrae_region_parkinson_OR(fila, reg_sana, ventana = 20)
    secuencias.append(str(reg_park))
    etiquetas.append("Riesgo_PD")
    rsIDs.append(fila["SNPs_symbol"])

    print(f"Seq {i} preparada")

Seq 0 preparada
Seq 1 preparada
Seq 2 preparada
Seq 3 preparada
Seq 4 preparada
Seq 5 preparada
Seq 6 preparada
Seq 7 preparada
Seq 8 preparada
Seq 9 preparada
Seq 10 preparada
Seq 11 preparada
Seq 12 preparada
Seq 13 preparada
Seq 14 preparada
Seq 15 preparada
Seq 16 preparada
Seq 17 preparada
Seq 18 preparada
Seq 19 preparada
Seq 20 preparada
Seq 21 preparada
Seq 22 preparada
Seq 23 preparada
Seq 24 preparada
Seq 25 preparada
Seq 26 preparada
Seq 27 preparada
Seq 28 preparada
Seq 29 preparada
Seq 30 preparada
Seq 31 preparada
Seq 32 preparada
Seq 33 preparada
Seq 34 preparada
Seq 35 preparada
Seq 36 preparada
Seq 37 preparada
Seq 38 preparada
Seq 39 preparada
Seq 40 preparada
Seq 41 preparada
Seq 42 preparada
Seq 43 preparada
Seq 44 preparada
Seq 45 preparada
Seq 46 preparada
Seq 47 preparada
Seq 48 preparada
Seq 49 preparada
Seq 50 preparada
Seq 51 preparada
Seq 52 preparada
Seq 53 preparada
Seq 54 preparada
Seq 55 preparada
Seq 56 preparada
Seq 57 preparada
Seq 58 preparada
Seq 59 preparada
Seq 60 preparada
Seq 61 preparada
Seq 62 preparada
Seq 63 preparada
Seq 64 preparada
Seq 65 preparada
Seq 66 preparada
Seq 67 preparada
Seq 68 preparada
Seq 69 preparada
Seq 70 preparada
Seq 71 preparada
Seq 72 preparada
Seq 73 preparada
Seq 74 preparada
Seq 75 preparada
Seq 76 preparada
Seq 77 preparada
Seq 78 preparada
Seq 79 preparada
Seq 80 preparada
Seq 81 preparada
Seq 82 preparada
Seq 83 preparada
Seq 84 preparada
Seq 85 preparada
Seq 86 preparada
Seq 87 preparada
Seq 88 preparada
Seq 89 preparada
Seq 90 preparada
Seq 91 preparada
Seq 92 preparada
Seq 93 preparada
Seq 94 preparada
Seq 95 preparada
Seq 96 preparada
Seq 97 preparada
Seq 98 preparada
Seq 99 preparada
Seq 100 preparada
Seq 101 preparada
Seq 102 preparada
Seq 103 preparada
Seq 104 preparada
Seq 105 preparada
Seq 106 preparada
Seq 107 preparada
Seq 108 preparada
Seq 109 preparada
Seq 110 preparada
Seq 111 preparada
Seq 112 preparada
Seq 113 preparada
Seq 114 preparada
Seq 115 preparada
Seq 116 preparada
Seq 117 preparada
Seq 118 preparada
Seq 119 preparada
Seq 120 preparada
Seq 121 preparada
Seq 122 preparada
Seq 123 preparada
Seq 124 preparada
Seq 125 preparada
Seq 126 preparada
Seq 127 preparada
Seq 128 preparada
Seq 129 preparada
Seq 130 preparada
Seq 131 preparada
Seq 132 preparada
Seq 133 preparada
Seq 134 preparada
Seq 135 preparada
Seq 136 preparada
Seq 137 preparada
Seq 138 preparada
Seq 139 preparada
Seq 140 preparada
Seq 141 preparada
Seq 142 preparada
Seq 143 preparada
Seq 144 preparada
Seq 145 preparada
Seq 146 preparada
Seq 147 preparada
Seq 148 preparada
Seq 149 preparada
Seq 150 preparada
Seq 151 preparada
Seq 152 preparada
Seq 153 preparada
Seq 154 preparada
Seq 155 preparada
Seq 156 preparada
Seq 157 preparada
Seq 158 preparada
Seq 159 preparada
Seq 160 preparada
Seq 161 preparada
Seq 162 preparada
Seq 163 preparada
Seq 164 preparada
Seq 165 preparada
Seq 166 preparada
Seq 167 preparada
Seq 168 preparada
Seq 169 preparada
Seq 170 preparada
Seq 171 preparada
Seq 172 preparada
Seq 173 preparada
Seq 174 preparada
Seq 175 preparada
Seq 176 preparada
Seq 177 preparada
Seq 178 preparada
Seq 179 preparada
Seq 180 preparada
Seq 181 preparada
Seq 182 preparada
Seq 183 preparada
Seq 184 preparada
Seq 185 preparada
Seq 186 preparada
Seq 187 preparada
Seq 188 preparada
Seq 189 preparada
Seq 190 preparada
Seq 191 preparada
Seq 192 preparada
Seq 193 preparada
Seq 194 preparada
Seq 195 preparada
Seq 196 preparada
Seq 197 preparada
Seq 198 preparada
Seq 199 preparada
Seq 200 preparada
Seq 201 preparada
Seq 202 preparada
Seq 203 preparada
Seq 204 preparada
Seq 205 preparada
Seq 206 preparada
Seq 207 preparada
Seq 208 preparada
Seq 209 preparada
Seq 210 preparada
Seq 211 preparada
Seq 212 preparada
Seq 213 preparada
Seq 214 preparada
Seq 215 preparada
Seq 216 preparada
Seq 217 preparada
Seq 218 preparada
Seq 219 preparada
Seq 220 preparada
Seq 221 preparada
Seq 222 preparada
Seq 223 preparada
Seq 224 preparada
Seq 225 preparada
Seq 226 preparada
Seq 227 preparada
Seq 228 preparada
Seq 229 preparada
Seq 230 preparada
Seq 231 preparada
Seq 232 preparada
Seq 233 preparada
Seq 234 preparada
Seq 235 preparada
Seq 236 preparada
Seq 237 preparada
Seq 238 preparada
Seq 239 preparada
Seq 240 preparada
Seq 241 preparada
Seq 242 preparada
Seq 243 preparada
Seq 244 preparada
Seq 245 preparada
Seq 246 preparada
Seq 247 preparada
Seq 248 preparada
Seq 249 preparada
Seq 250 preparada
Seq 251 preparada
Seq 252 preparada
Seq 253 preparada
Seq 254 preparada
Seq 255 preparada
Seq 256 preparada
Seq 257 preparada
Seq 258 preparada
Seq 259 preparada
Seq 260 preparada
Seq 261 preparada
Seq 262 preparada
Seq 263 preparada
Seq 264 preparada
Seq 265 preparada
Seq 266 preparada
Seq 267 preparada
Seq 268 preparada
Seq 269 preparada
Seq 270 preparada
Seq 271 preparada
Seq 272 preparada
Seq 273 preparada
Seq 274 preparada
Seq 275 preparada
Seq 276 preparada
Seq 277 preparada
Seq 278 preparada
Seq 279 preparada
Seq 280 preparada
Seq 281 preparada
Seq 282 preparada
Seq 283 preparada
Seq 284 preparada
Seq 285 preparada
Seq 286 preparada
Seq 287 preparada
Seq 288 preparada
Seq 289 preparada
Seq 290 preparada
Seq 291 preparada
Seq 292 preparada
Seq 293 preparada
Seq 294 preparada
Seq 295 preparada
Seq 296 preparada
Seq 297 preparada
Seq 298 preparada
Seq 299 preparada
Seq 300 preparada
Seq 301 preparada
Seq 302 preparada
Seq 303 preparada
Seq 304 preparada
Seq 305 preparada
Seq 306 preparada
Seq 307 preparada
Seq 308 preparada
Seq 309 preparada
Seq 310 preparada
Seq 311 preparada
Seq 312 preparada
Seq 313 preparada
Seq 314 preparada
Seq 315 preparada
Seq 316 preparada
Seq 317 preparada
Seq 318 preparada
Seq 319 preparada
Seq 320 preparada
Seq 321 preparada
Seq 322 preparada
Seq 323 preparada
Seq 324 preparada
Seq 325 preparada
Seq 326 preparada
Seq 327 preparada
Seq 328 preparada
Seq 329 preparada
Seq 330 preparada
Seq 331 preparada
Seq 332 preparada
Seq 333 preparada
Seq 334 preparada
Seq 335 preparada
Seq 336 preparada
Seq 337 preparada
Seq 338 preparada
Seq 339 preparada
Seq 340 preparada
Seq 341 preparada
Seq 342 preparada
Seq 343 preparada
Seq 344 preparada
Seq 345 preparada
Seq 346 preparada
Seq 347 preparada
Seq 348 preparada
Seq 349 preparada
Seq 350 preparada
Seq 351 preparada
Seq 352 preparada
Seq 353 preparada
Seq 354 preparada
Seq 355 preparada
Seq 356 preparada
Seq 357 preparada
Seq 358 preparada
Seq 359 preparada
Seq 360 preparada
Seq 361 preparada
Seq 362 preparada
Seq 363 preparada
Seq 364 preparada
Seq 365 preparada
Seq 366 preparada
Seq 367 preparada
Seq 368 preparada
Seq 369 preparada
Seq 370 preparada
Seq 371 preparada
Seq 372 preparada
Seq 373 preparada
Seq 374 preparada
Seq 375 preparada
Seq 376 preparada
Seq 377 preparada
Seq 378 preparada
Seq 379 preparada
Seq 380 preparada
Seq 381 preparada
Seq 382 preparada
Seq 383 preparada
Seq 384 preparada
Seq 385 preparada
Seq 386 preparada
Seq 387 preparada
Seq 388 preparada
Seq 389 preparada
Seq 390 preparada
Seq 391 preparada
Seq 392 preparada
Seq 393 preparada
Seq 394 preparada
Seq 395 preparada
Seq 396 preparada
Seq 397 preparada
Seq 398 preparada
Seq 399 preparada
Seq 400 preparada
Seq 401 preparada
Seq 402 preparada
Seq 403 preparada
Seq 404 preparada
Seq 405 preparada
Seq 406 preparada
Seq 407 preparada
Seq 408 preparada
Seq 409 preparada
Seq 410 preparada
Seq 411 preparada
Seq 412 preparada
Seq 413 preparada
Seq 414 preparada
Seq 415 preparada
Seq 416 preparada
Seq 417 preparada
Seq 418 preparada
Seq 419 preparada
Seq 420 preparada
Seq 421 preparada
Seq 422 preparada
Seq 423 preparada
Seq 424 preparada
Seq 425 preparada
Seq 426 preparada
Seq 427 preparada
Seq 428 preparada
Seq 429 preparada
Seq 430 preparada
Seq 431 preparada
Seq 432 preparada
Seq 433 preparada
Seq 434 preparada
Seq 435 preparada
Seq 436 preparada
Seq 437 preparada
Seq 438 preparada
Seq 439 preparada
Seq 440 preparada
Seq 441 preparada
Seq 442 preparada
Seq 443 preparada
Seq 444 preparada
Seq 445 preparada
Seq 446 preparada
Seq 447 preparada
Seq 448 preparada
Seq 449 preparada
Seq 450 preparada
Seq 451 preparada
Seq 452 preparada
Seq 453 preparada
Seq 454 preparada
Seq 455 preparada
Seq 456 preparada
Seq 457 preparada
Seq 458 preparada
Seq 459 preparada
Seq 460 preparada
Seq 461 preparada
Seq 462 preparada
Seq 463 preparada
Seq 464 preparada
Seq 465 preparada
Seq 466 preparada
Seq 467 preparada
Seq 468 preparada
Seq 469 preparada
Seq 470 preparada
Seq 471 preparada
Seq 472 preparada
Seq 473 preparada
Seq 474 preparada
Seq 475 preparada
Seq 476 preparada
Seq 477 preparada
Seq 478 preparada
Seq 479 preparada
Seq 480 preparada
Seq 481 preparada
Seq 482 preparada
Seq 483 preparada
Seq 484 preparada
Seq 485 preparada
Seq 486 preparada
Seq 487 preparada
Seq 488 preparada
Seq 489 preparada
Seq 490 preparada
Seq 491 preparada
Seq 492 preparada
Seq 493 preparada
Seq 494 preparada
Seq 495 preparada
Seq 496 preparada
Seq 497 preparada
Seq 498 preparada
Seq 499 preparada
Seq 500 preparada
Seq 501 preparada
Seq 502 preparada
Seq 503 preparada
Seq 504 preparada
Seq 505 preparada
Seq 506 preparada
Seq 507 preparada
Seq 508 preparada
Seq 509 preparada
Seq 510 preparada
Seq 511 preparada
Seq 512 preparada
Seq 513 preparada
Seq 514 preparada
Seq 515 preparada
Seq 516 preparada
Seq 517 preparada
Seq 518 preparada
Seq 519 preparada
Seq 520 preparada
Seq 521 preparada
Seq 522 preparada
Seq 523 preparada
Seq 524 preparada
Seq 525 preparada
Seq 526 preparada
Seq 527 preparada
Seq 528 preparada
Seq 529 preparada
Seq 530 preparada
Seq 531 preparada
Seq 532 preparada
Seq 533 preparada
Seq 534 preparada
Seq 535 preparada
Seq 536 preparada
Seq 537 preparada
Seq 538 preparada
Seq 539 preparada
Seq 540 preparada
Seq 541 preparada
Seq 542 preparada
Seq 543 preparada
Seq 544 preparada
Seq 545 preparada
Seq 546 preparada
Seq 547 preparada
Seq 548 preparada
Seq 549 preparada
Seq 550 preparada
Seq 551 preparada
Seq 552 preparada
Seq 553 preparada
Seq 554 preparada
Seq 555 preparada
Seq 556 preparada
Seq 557 preparada
Seq 558 preparada
Seq 559 preparada
Seq 560 preparada
Seq 561 preparada
Seq 562 preparada
Seq 563 preparada
Seq 564 preparada
Seq 565 preparada
Seq 566 preparada
Seq 567 preparada
Seq 568 preparada
Seq 569 preparada
Seq 570 preparada
Seq 571 preparada
Seq 572 preparada
Seq 573 preparada
Seq 574 preparada
Seq 575 preparada
Seq 576 preparada
Seq 577 preparada
Seq 578 preparada
Seq 579 preparada
Seq 580 preparada
Seq 581 preparada
Seq 582 preparada
Seq 583 preparada
Seq 584 preparada
Seq 585 preparada
Seq 586 preparada
Seq 587 preparada
Seq 588 preparada
Seq 589 preparada
Seq 590 preparada
Seq 591 preparada
Seq 592 preparada
Seq 593 preparada
Seq 594 preparada
Seq 595 preparada
Seq 596 preparada
Seq 597 preparada
Seq 598 preparada
Seq 599 preparada
Seq 600 preparada
Seq 601 preparada
Seq 602 preparada
Seq 603 preparada
Seq 604 preparada
Seq 605 preparada
Seq 606 preparada
Seq 607 preparada
Seq 608 preparada
Seq 609 preparada
Seq 610 preparada
Seq 611 preparada
Seq 612 preparada
Seq 613 preparada
Seq 614 preparada
Seq 615 preparada
Seq 616 preparada
Seq 617 preparada
Seq 618 preparada
Seq 619 preparada
Seq 620 preparada
Seq 621 preparada
Seq 622 preparada
Seq 623 preparada
Seq 624 preparada
Seq 625 preparada
Seq 626 preparada
Seq 627 preparada
Seq 628 preparada
Seq 629 preparada
Seq 630 preparada
Seq 631 preparada
Seq 632 preparada
Seq 633 preparada
Seq 634 preparada
Seq 635 preparada
Seq 636 preparada
Seq 637 preparada
Seq 638 preparada
Seq 639 preparada
Seq 640 preparada
Seq 641 preparada
Seq 642 preparada
Seq 643 preparada
Seq 644 preparada
Seq 645 preparada
Seq 646 preparada
Seq 647 preparada
Seq 648 preparada
Seq 649 preparada
Seq 650 preparada
Seq 651 preparada
Seq 652 preparada
Seq 653 preparada
Seq 654 preparada
Seq 655 preparada
Seq 656 preparada
Seq 657 preparada
Seq 658 preparada
Seq 659 preparada
Seq 660 preparada
Seq 661 preparada
Seq 662 preparada
Seq 663 preparada
Seq 664 preparada
Seq 665 preparada
Seq 666 preparada
Seq 667 preparada
Seq 668 preparada
Seq 669 preparada
Seq 670 preparada
Seq 671 preparada
Seq 672 preparada
Seq 673 preparada
Seq 674 preparada
Seq 675 preparada
Seq 676 preparada
Seq 677 preparada
Seq 678 preparada
Seq 679 preparada
Seq 680 preparada
Seq 681 preparada
Seq 682 preparada
Seq 683 preparada
Seq 684 preparada
Seq 685 preparada
Seq 686 preparada
Seq 687 preparada
Seq 688 preparada
Seq 689 preparada
Seq 690 preparada
Seq 691 preparada
Seq 692 preparada
Seq 693 preparada
Seq 694 preparada
Seq 695 preparada
Seq 696 preparada
Seq 697 preparada
Seq 698 preparada
Seq 699 preparada
Seq 700 preparada
Seq 701 preparada
Seq 702 preparada
Seq 703 preparada
Seq 704 preparada
Seq 705 preparada
Seq 706 preparada
Seq 707 preparada
Seq 708 preparada

In [ ]:
df_base_final_or = pd.DataFrame(list(zip(secuencias, etiquetas)), columns = ["Secuencia", "Etiqueta"])

In [ ]:
df_base_final_or

In [32]:
df_base_final_or.iloc[0]["Secuencia"]

'attcatcttccactgtgctaggaaggagaatgttcagaaac'

In [33]:
df_base_final_or.iloc[1]["Secuencia"]

'attcatcttccactgtgctatgaaggagaatgttcagaaac'

In [35]:
df_base_final_or.to_csv('datosGene4PD/base_flanqueantes_20_OR_1418.csv', index = False)

In [32]:
df_base_final_or_rsid = pd.DataFrame(list(zip(secuencias, etiquetas, rsIDs)), columns = ["Secuencia", "Etiqueta", "rsID"])

In [33]:
df_base_final_or_rsid

                                      Secuencia   Etiqueta         rsID
0     attcatcttccactgtgctaggaaggagaatgttcagaaac       Sano  rs757765789
1     attcatcttccactgtgctatgaaggagaatgttcagaaac  Riesgo_PD  rs757765789
2     tgctaaccctttttattttcagtgaactaatgcaggaaaaa       Sano    rs1994090
3     tgctaaccctttttattttccgtgaactaatgcaggaaaaa  Riesgo_PD    rs1994090
4     accagtcatctgtcaacttaatagcatacaaaaagacatca       Sano    rs2708453
...                                         ...        ...          ...
1413  tacatcatctttaatattttttcactatttattctgaatac  Riesgo_PD    rs1941685
1414  tgctgaatattttaagcctacaattgagacctactgctcag       Sano   rs77351827
1415  tgctgaatattttaagcctataattgagacctactgctcag  Riesgo_PD   rs77351827
1416  taggtttaaaaactgggcatgtctcagagggcctatttatt       Sano    rs2248244
1417  taggtttaaaaactgggcatatctcagagggcctatttatt  Riesgo_PD    rs2248244

[1418 rows x 3 columns]

In [34]:
df_base_final_or_rsid.to_csv('datosGene4PD/base_flanqueantes_20_OR_1418_con_rsid.csv', index = False)