In [5]:
import pandas as pd
import numpy as np
import requests
import time
import mygene

from Bio import Entrez, SeqIO

In [2]:
df_final = pd.read_csv("datosGene4PD/coordenadas_genes.csv", sep = ",", index_col = False)

In [3]:
df_final

,Chr,gene_symbol,inicio,SNP_position,fin,effect_allele,alternate_allele,cadena
0,6,GPR126,142622991,142758601,142767403,T,G,1.0
1,1,SYT11,155829300,155839054,155854990,C,T,1.0
2,12,SLC2A13,40148823,40428561,40499891,G,T,-1.0
3,12,SLC2A13,40148823,40478652,40499891,G,T,-1.0
4,12,SLC2A13,40148823,40474147,40499891,C,T,-1.0
...,...,...,...,...,...,...,...,...
628,17,BRIP1,59758627,59917366,59940882,T,C,-1.0
629,17,DNAH17,76419778,76425480,76573476,A,T,-1.0
630,18,ASXL3,31158579,31304318,31331156,T,G,1.0
631,20,CRLS1,5986736,6006041,6020699,T,C,1.0
632,21,DYRK1A,38738092,38852361,38889753,A,G,1.0

In [8]:
lista_symbols = []

for i in range(len(df_final)):
    lista_symbols.append(df_final.iloc[i]["gene_symbol"])

In [6]:
Entrez.email = "jbs1009@alu.ubu.es"

def descargar_secuencia(gene_symbol):    
    
    query = f"{gene_symbol}[Gene Name] AND Homo sapiens[Organism] AND refseq[filter] AND biomol_mrna[prop]"
    
    try:
        
        handle = Entrez.esearch(db = "nucleotide", term = query, retmax = 1)
        record = Entrez.read(handle)
        handle.close()
        
        if not record["IdList"]:
            return None
        
        seq_id = record["IdList"][0]
        
        fetch_handle = Entrez.efetch(db = "nucleotide", id = seq_id, rettype = "fasta", retmode = "text")
        
        seq_record = SeqIO.read(fetch_handle, "fasta")
        fetch_handle.close()
        
        return str(seq_record.seq)
    
    except Exception as e:
        
        print(f"Error al descargar {gene_symbol}: {e}")
        return None

In [12]:
secuencias_guardadas = {}

for gen in lista_symbols:
    print(f"Buscando: {gen}", end = " ")
    
    secuencia = descargar_secuencia(gen)
    
    if secuencia:
        secuencias_guardadas[gen] = secuencia
        print("Encontrado.")
    else:
        print("No encontrado.")
    
    time.sleep(0.5)

Buscando: GPR126 Encontrado.
Buscando: SYT11 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: SERPINA1 Encontrado.
Buscando: SERPINA1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: SPPL2C Encontrado.
Buscando: HLA-DRA Encontrado.
Buscando: DGKQ Encontrado.
Buscando: NSF Encontrado.
Buscando: GAK Encontrado.
Buscando: WNT3 Encontrado.
Buscando: CSMD1 Encontrado.
Buscando: TAS2R19 Encontrado.
Buscando: WNT3 Encontrado.
Buscando: UNC13B Encontrado.
Buscando: LINC00693 No encontrado.
Buscando: MPHOSPH10 Encontrado.
Buscando: ZNF519 Encontrado.
Buscando: AAK1 Encontrado.
Buscando: CDH6 Encontrado.
Buscando: GRB10 Encontrado.
Buscando: PIK3CD Encontrado.
Buscando: SNCA Encontrado.
Buscando: PLA2R1 Encontrado.
Buscando: SH3GL2 Encontrado.
Buscando: PLA2R1 Encontrado.
Buscando: CAST Encontrado.
Buscando: SLCO3A1 Encontrado.
Buscando: SPPL2C Encontrado.
Buscando: DNAH11 Encontrado.
Buscando: PLA2R1 Encontrado.
Buscando: PLEKHM1 Encontrado.
Buscando: CDH6 Encontrado.
Buscando: GABRB3 Encontrado.
Buscando: RNF130 Encontrado.
Buscando: SLC22A3 Encontrado.
Buscando: LINC02210 No encontrado.
Buscando: MAPT Encontrado.
Buscando: SPPL2C Encontrado.
Buscando: ANKRD36 Encontrado.
Buscando: ANKRD36 Encontrado.
Buscando: MED13 Encontrado.
Buscando: TMEM2 Encontrado.
Buscando: ABCA3 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: AP3B1 Encontrado.
Buscando: AP3B1 Encontrado.
Buscando: ENSA Encontrado.
Buscando: LINC00693 No encontrado.
Buscando: ABCA3 Encontrado.
Buscando: HLX-AS1 No encontrado.
Buscando: BST1 Encontrado.
Buscando: FER Encontrado.
Buscando: SNCA Encontrado.
Buscando: PGGHG Encontrado.
Buscando: PRKG1 Encontrado.
Buscando: CHN2 Encontrado.
Buscando: FER Encontrado.
Buscando: GAK Encontrado.
Buscando: SLC25A48 Encontrado.
Buscando: MAPT Encontrado.
Buscando: MAPT Encontrado.
Buscando: TMEM175 Encontrado.
Buscando: DGKQ Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: LINC02210 No encontrado.
Buscando: AP3B1 Encontrado.
Buscando: CARMIL1 Encontrado.
Buscando: CSMD1 Encontrado.
Buscando: IL2RA Encontrado.
Buscando: IL2RA Encontrado.
Buscando: NEDD9 Encontrado.
Buscando: NEDD9 Encontrado.
Buscando: PGGHG Encontrado.
Buscando: RBFOX1 Encontrado.
Buscando: RBFOX1 Encontrado.
Buscando: TMPRSS12 Encontrado.
Buscando: ZNF804B Encontrado.
Buscando: ZNF804B Encontrado.
Buscando: NUPL2 Encontrado.
Buscando: APOE Encontrado.
Buscando: MAPT Encontrado.
Buscando: TMEM175 Encontrado.
Buscando: SNCA Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: MCCC1 Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA Encontrado.
Buscando: BST1 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: FAM47E-STBD1 Encontrado.
Buscando: HIP1R Encontrado.
Buscando: C17orf69 No encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA Encontrado.
Buscando: NDUFAF2 Encontrado.
Buscando: RAB7L1 Encontrado.
Buscando: NSF Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: SPPL2C Encontrado.
Buscando: SPPL2C Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: MAPT Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: MAPT Encontrado.
Buscando: MAPT Encontrado.
Buscando: MAPT Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: TMEM229B Encontrado.
Buscando: MAPT Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: SPPL2C Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: LINC02210 No encontrado.
Buscando: CRHR1 Encontrado.
Buscando: WNT3 Encontrado.
Buscando: NSF Encontrado.
Buscando: GPNMB Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: INPP5F Encontrado.
Buscando: SH3GL2 Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: NSF Encontrado.
Buscando: KIAA1267 Encontrado.
Buscando: MAPT Encontrado.
Buscando: SETD1A Encontrado.
Buscando: SNCA Encontrado.
Buscando: MAPT-AS1 No encontrado.
Buscando: GPNMB Encontrado.
Buscando: SLC41A1 Encontrado.
Buscando: BCKDK Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: DGKQ Encontrado.
Buscando: CTSB Encontrado.
Buscando: CCDC62 Encontrado.
Buscando: RIT2 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: ITPKB Encontrado.
Buscando: FAM47E Encontrado.
Buscando: FAM47E-STBD1 Encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA Encontrado.
Buscando: MAP4K4 Encontrado.
Buscando: GCH1 Encontrado.
Buscando: SNCA Encontrado.
Buscando: NSF Encontrado.
Buscando: PLEKHM1 Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: GPR65 Encontrado.
Buscando: CASC16 No encontrado.
Buscando: HLA-DRA Encontrado.
Buscando: MCCC1 Encontrado.
Buscando: SIPA1L2 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: FAM47E-STBD1 Encontrado.
Buscando: MAPT-AS1 No encontrado.
Buscando: WNT3 Encontrado.
Buscando: BST1 Encontrado.
Buscando: SNCA Encontrado.
Buscando: STK39 Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: SNCA Encontrado.
Buscando: GAK Encontrado.
Buscando: SLC41A1 Encontrado.
Buscando: BST1 Encontrado.
Buscando: NUCKS1 Encontrado.
Buscando: BST1 Encontrado.
Buscando: SNCA Encontrado.
Buscando: BST1 Encontrado.
Buscando: SNCA Encontrado.
Buscando: IP6K2 Encontrado.
Buscando: NSF Encontrado.
Buscando: MIR4519 No encontrado.
Buscando: MCCC1 Encontrado.
Buscando: NSF Encontrado.
Buscando: ITGA8 Encontrado.
Buscando: ITGA8 Encontrado.
Buscando: BST1 Encontrado.
Buscando: SLC41A1 Encontrado.
Buscando: BIN3 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: MCCC1 Encontrado.
Buscando: SCN2A Encontrado.
Buscando: SNCA Encontrado.
Buscando: ITIH1 Encontrado.
Buscando: TMEM175 Encontrado.
Buscando: SNCA Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: SNCA Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: SNCA Encontrado.
Buscando: NUCKS1 Encontrado.
Buscando: GAK Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: MCCC1 Encontrado.
Buscando: SLC45A3 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: PM20D1 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: SLC41A1 Encontrado.
Buscando: SNCA Encontrado.
Buscando: MCCC1 Encontrado.
Buscando: DLG2 Encontrado.
Buscando: NSF Encontrado.
Buscando: SLC41A1 Encontrado.
Buscando: CCDC82 Encontrado.
Buscando: TMC3-AS1 No encontrado.
Buscando: DGKQ Encontrado.
Buscando: RIT2 Encontrado.
Buscando: RAB38 Encontrado.
Buscando: MX2 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: DLG2 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: FAM47E-STBD1 Encontrado.
Buscando: LAMP3 Encontrado.
Buscando: LAMP3 Encontrado.
Buscando: SNCA Encontrado.
Buscando: COL13A1 Encontrado.
Buscando: WBP1L Encontrado.
Buscando: PM20D1 Encontrado.
Buscando: ZP3 Encontrado.
Buscando: RAI1 Encontrado.
Buscando: CNNM2 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: CNNM2 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: CCDC62 Encontrado.
Buscando: PABPN1L Error al descargar PABPN1L: Remote end closed connection without response
No encontrado.
Buscando: PLEKHM1 Encontrado.
Buscando: SPPL2C Encontrado.
Buscando: SPPL2C Encontrado.
Buscando: GFPT2 Encontrado.
Buscando: MAPT Encontrado.
Buscando: GFPT2 Encontrado.
Buscando: C17orf69 No encontrado.
Buscando: BRINP1 Encontrado.
Buscando: DBC1 Encontrado.
Buscando: GFPT2 Encontrado.
Buscando: MAPT Encontrado.
Buscando: NPAS3 Encontrado.
Buscando: DCUN1D1 Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: DCUN1D1 Encontrado.
Buscando: SREBF1 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: CNTN1 Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: SNCA Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: NSF Encontrado.
Buscando: SNCA Encontrado.
Buscando: RAI1 Encontrado.
Buscando: MCCC1 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: CNTN1 Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: DGKQ Encontrado.
Buscando: MCCC1 Encontrado.
Buscando: TCEANC2 Encontrado.
Buscando: HTR2A-AS1 No encontrado.
Buscando: LDLRAD1 Encontrado.
Buscando: SNCA Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA-AS1 No encontrado.
Buscando: SNCA Encontrado.
Buscando: KCNIP4 Encontrado.
Buscando: MAPT Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: DSCAM Encontrado.
Buscando: SNCA Encontrado.
Buscando: GAK Encontrado.
Buscando: FAM47E Encontrado.
Buscando: MCCC1 Encontrado.
Buscando: CAST Encontrado.
Buscando: TASP1 Encontrado.
Buscando: ITGA8 Encontrado.
Buscando: TOM1L2 Encontrado.
Buscando: LRP1B Encontrado.
Buscando: SNCA Encontrado.
Buscando: RBMS3 Encontrado.
Buscando: EHMT2 Encontrado.
Buscando: RAI1 Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: SEMA5A Encontrado.
Buscando: FAM47E Encontrado.
Buscando: LRP1B Encontrado.
Buscando: FAM47E Encontrado.
Buscando: EHMT2 Encontrado.
Buscando: LRP1B Encontrado.
Buscando: CNTN1 Encontrado.
Buscando: CCDC158 Encontrado.
Buscando: DRG2 Encontrado.
Buscando: C18orf1 Encontrado.
Buscando: PDE10A Encontrado.
Buscando: MDGA2 Encontrado.
Buscando: CLRN3 Encontrado.
Buscando: SNCA Encontrado.
Buscando: SPOCK1 Encontrado.
Buscando: POM121L2 Encontrado.
Buscando: TRPM3 Encontrado.
Buscando: AGAP1 Encontrado.
Buscando: CAST Encontrado.
Buscando: SNCA Encontrado.
Buscando: TTLL5 Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: ABCA13 Encontrado.
Buscando: DRG2 Encontrado.
Buscando: REC114 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: KLHL7 Encontrado.
Buscando: MCCC1 Encontrado.
Buscando: MYO1E Encontrado.
Buscando: RBMS3 Encontrado.
Buscando: TTLL5 Encontrado.
Buscando: TENM4 Encontrado.
Buscando: TOM1L2 Encontrado.
Buscando: PRTFDC1 Encontrado.
Buscando: KLHL7-AS1 No encontrado.
Buscando: LRP1B Encontrado.
Buscando: RIT2 Encontrado.
Buscando: EPB41L3 Encontrado.
Buscando: ABCA13 Encontrado.
Buscando: SUSD3 Encontrado.
Buscando: GABRB3 Encontrado.
Buscando: IL5RA Encontrado.
Buscando: SCARB2 Encontrado.
Buscando: LRP1B Encontrado.
Buscando: WDHD1 Encontrado.
Buscando: RBFOX1 Encontrado.
Buscando: TOM1L2 Encontrado.
Buscando: BST1 Encontrado.
Buscando: SNCA Encontrado.
Buscando: MYO15A Encontrado.
Buscando: TOM1L2 Encontrado.
Buscando: KDM2B Encontrado.
Buscando: MAPT Encontrado.
Buscando: KLHL7 Encontrado.
Buscando: KLHL7 Encontrado.
Buscando: KLHL7 Encontrado.
Buscando: KLHL7 Encontrado.
Buscando: LRP1B Encontrado.
Buscando: LRP1B Encontrado.
Buscando: MUC19 Encontrado.
Buscando: DCDC2C Encontrado.
Buscando: DCUN1D1 Encontrado.
Buscando: LRP1B Encontrado.
Buscando: SCARB2 Encontrado.
Buscando: ACTR3B Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: RIT2 Encontrado.
Buscando: MAPT Encontrado.
Buscando: CCNYL2 No encontrado.
Buscando: KLHL7 Encontrado.
Buscando: GID4 Encontrado.
Buscando: SNCA Encontrado.
Buscando: ARHGAP24 Encontrado.
Buscando: KLHL7 Encontrado.
Buscando: WDHD1 Encontrado.
Buscando: PLCB4 Encontrado.
Buscando: ITGA6 Encontrado.
Buscando: GAK Encontrado.
Buscando: MECOM Encontrado.
Buscando: LARP1B Encontrado.
Buscando: DSCAM Encontrado.
Buscando: SNCA Encontrado.
Buscando: CNTNAP5 Encontrado.
Buscando: ARHGAP24 Encontrado.
Buscando: CNTNAP5 Encontrado.
Buscando: PTPRT Encontrado.
Buscando: C3orf20 Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: SCAMP5 Encontrado.
Buscando: MVB12B Encontrado.
Buscando: TMEM200C Encontrado.
Buscando: CNTNAP5 Encontrado.
Buscando: TOM1L2 Encontrado.
Buscando: TRIM2 Encontrado.
Buscando: MVB12B Encontrado.
Buscando: ITGA8 Encontrado.
Buscando: GALNT3 Encontrado.
Buscando: SYT17 Encontrado.
Buscando: PSORS1C1 Encontrado.
Buscando: SYT17 Encontrado.
Buscando: EIF4A3 Encontrado.
Buscando: SENP7 Encontrado.
Buscando: ANK2 Encontrado.
Buscando: GID4 Encontrado.
Buscando: TMEM175 Encontrado.
Buscando: CALN1 Encontrado.
Buscando: MVB12B Encontrado.
Buscando: PRDM2 Encontrado.
Buscando: SLC24A2 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: FAM47E-STBD1 Encontrado.
Buscando: ADAMTS6 Encontrado.
Buscando: MUC19 Encontrado.
Buscando: CNTLN Encontrado.
Buscando: LAMP3 Encontrado.
Buscando: PRKAA1 Encontrado.
Buscando: TOM1L2 Encontrado.
Buscando: CNTN1 Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: JARID2 Encontrado.
Buscando: SYT17 Encontrado.
Buscando: TRIO Encontrado.
Buscando: SNCA-AS1 No encontrado.
Buscando: TRIML2 Encontrado.
Buscando: SNCA Encontrado.
Buscando: ADAMTS6 Encontrado.
Buscando: KLHL7 Encontrado.
Buscando: SENP7 Encontrado.
Buscando: SCAMP5 Encontrado.
Buscando: KLHL7 Encontrado.
Buscando: RBMS3 Encontrado.
Buscando: SPPL2C Encontrado.
Buscando: ACTN4 Encontrado.
Buscando: SREBF1 Encontrado.
Buscando: PTPRT Encontrado.
Buscando: CNTN1 Encontrado.
Buscando: IMPG2 Encontrado.
Buscando: RETREG3 Encontrado.
Buscando: SYT17 Encontrado.
Buscando: FAM167A Encontrado.
Buscando: C8orf12 No encontrado.
Buscando: TIAL1 Encontrado.
Buscando: RIT2 Encontrado.
Buscando: GAK Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: SMIM15-AS1 No encontrado.
Buscando: LRRK2 Encontrado.
Buscando: GABRG3 Encontrado.
Buscando: HMCES Encontrado.
Buscando: KLHL7 Encontrado.
Buscando: BAG6 Encontrado.
Buscando: ABHD16A Encontrado.
Buscando: DAPK1 Encontrado.
Buscando: FAM171A2 Encontrado.
Buscando: MAPT Encontrado.
Buscando: TMEM163 Encontrado.
Buscando: GCH1 Encontrado.
Buscando: GAK Encontrado.
Buscando: DSCAM Encontrado.
Buscando: TOM1L2 Encontrado.
Buscando: MYO15A Encontrado.
Buscando: SCARB2 Encontrado.
Buscando: DRG2 Encontrado.
Buscando: BTNL2 Encontrado.
Buscando: RIT2 Encontrado.
Buscando: CPNE4 Encontrado.
Buscando: MYH16 Encontrado.
Buscando: KDM2B Encontrado.
Buscando: DFNA5 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: PRRC2A Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: SLC41A1 Encontrado.
Buscando: FRMD4A Encontrado.
Buscando: LOC441666 No encontrado.
Buscando: LARP1B Encontrado.
Buscando: SYT17 Encontrado.
Buscando: MAPT Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: LRRK2 Encontrado.
Buscando: LARP1B Encontrado.
Buscando: CRHR1 Encontrado.
Buscando: MBD5 Encontrado.
Buscando: RIT2 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: LARP1B Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: TOM1L2 Encontrado.
Buscando: LRP1B Encontrado.
Buscando: NTF3 Encontrado.
Buscando: DRC3 Encontrado.
Buscando: KANK1 Encontrado.
Buscando: KIF1BP Encontrado.
Buscando: COL2A1 Encontrado.
Buscando: GRIP1 Encontrado.
Buscando: CCDC102B Encontrado.
Buscando: DOCK5 Encontrado.
Buscando: PLS1 Encontrado.
Buscando: PLS1 Encontrado.
Buscando: CYP1B1 Encontrado.
Buscando: C2orf58 No encontrado.
Buscando: TACC2 Encontrado.
Buscando: PAMR1 Encontrado.
Buscando: DGKQ Encontrado.
Buscando: KANK1 Encontrado.
Buscando: HDAC7A Encontrado.
Buscando: SP140 Encontrado.
Buscando: KANK1 Encontrado.
Buscando: ETV6 Encontrado.
Buscando: BIN3 Encontrado.
Buscando: FAM47E Encontrado.
Buscando: PLEKHN1 Encontrado.
Buscando: CCDC149 Encontrado.
Buscando: SERPING1 Encontrado.
Buscando: LINC02405 No encontrado.
Buscando: ETV6 Encontrado.
Buscando: SLC41A1 Encontrado.
Buscando: CCAR2 Encontrado.
Buscando: SIPA1L2 Encontrado.
Buscando: VNN2 Encontrado.
Buscando: SLC41A1 Encontrado.
Buscando: JCAD Encontrado.
Buscando: RPH3AL Encontrado.
Buscando: LINC02210 No encontrado.
Buscando: FMN1 Encontrado.
Buscando: CBARA1 Encontrado.
Buscando: GPNMB Encontrado.
Buscando: NRXN1 Encontrado.
Buscando: LINC01679 No encontrado.
Buscando: PRUNE2 Encontrado.
Buscando: DDAH1 Encontrado.
Buscando: LRP1B Encontrado.
Buscando: ATR Encontrado.
Buscando: CPXM1 Encontrado.
Buscando: RBFOX1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: MAPT-AS1 No encontrado.
Buscando: MMRN1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: CDCP1 Encontrado.
Buscando: MAPT-AS1 No encontrado.
Buscando: MAPT Encontrado.
Buscando: MAPT Encontrado.
Buscando: KANSL1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: MAPT Encontrado.
Buscando: MCPH1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: ZMAT3 Encontrado.
Buscando: CDCP1 Encontrado.
Buscando: AXIN1 Encontrado.
Buscando: LRP1B Encontrado.
Buscando: SP140 Encontrado.
Buscando: SNCA Encontrado.
Buscando: SEMA3E Encontrado.
Buscando: MAPT Encontrado.
Buscando: ZNF554 Encontrado.
Buscando: MAPT Encontrado.
Buscando: ZNF615 Encontrado.
Buscando: DDX18 Encontrado.
Buscando: MAPT Encontrado.
Buscando: HIP1R Encontrado.
Buscando: COL5A2 Encontrado.
Buscando: SPATA21 Encontrado.
Buscando: SLC2A13 Encontrado.
Buscando: ANGPT2 Encontrado.
Buscando: MCPH1 Encontrado.
Buscando: TAP2 Encontrado.
Buscando: RAD51B Encontrado.
Buscando: FBXO34 Encontrado.
Buscando: SNCA Encontrado.
Buscando: SNCA Encontrado.
Buscando: FBXO34 Encontrado.
Buscando: WNK1 Encontrado.
Buscando: MAPT Encontrado.
Buscando: TIAL1 Encontrado.
Buscando: NOTCH4 Encontrado.
Buscando: KCNS3 Encontrado.
Buscando: KCNIP3 Encontrado.
Buscando: LINC00693 No encontrado.
Buscando: KPNA1 Encontrado.
Buscando: MED12L Encontrado.
Buscando: SPTSSB Encontrado.
Buscando: LCORL Encontrado.
Buscando: CLCN3 Encontrado.
Buscando: PAM Encontrado.
Buscando: TRIM40 Encontrado.
Buscando: FAM49B Encontrado.
Buscando: UBAP2 Encontrado.
Buscando: GBF1 Encontrado.
Buscando: RNF141 Encontrado.
Buscando: CAB39L Encontrado.
Buscando: MIPOL1 Encontrado.
Buscando: RPS6KL1 Encontrado.
Buscando: CD19 Encontrado.
Buscando: NOD2 Encontrado.
Buscando: CNOT1 Encontrado.
Buscando: CHRNB1 Encontrado.
Buscando: UBTF Encontrado.
Buscando: FAM171A2 Encontrado.
Buscando: BRIP1 Encontrado.
Buscando: DNAH17 Encontrado.
Buscando: ASXL3 Encontrado.
Buscando: CRLS1 Encontrado.
Buscando: DYRK1A Encontrado.

In [15]:
len(secuencias_guardadas)

257

In [17]:
df_secs = pd.DataFrame(list(secuencias_guardadas.items()), columns = ["gene_symbol", "secuencia"])

In [18]:
df_secs

    gene_symbol                                          secuencia
0        GPR126  AGGAGTAACAGGCACCGCTCCTCAGTCCAGAGGCCTGGCCCTGCCA...
1         SYT11  AGCGCATCCCCGGAGCATCTTAAGAGCTGAGCGCAGCTGACAACTA...
2       SLC2A13  TGACAGACACACACATAAATGCACAAATAATTCTGGCTAACTTCAC...
3         LRRK2  GGGGCCCGCGGGGAGCGCTGGCTGCGGGCGGTGAGCTGAGCTCGCC...
4      SERPINA1  AGAGTCCTGAGCTGAACCAAGAAGGAGGAGGGGGTCGGGCCTCCGA...
..          ...                                                ...
252       BRIP1  CGCACGGCTTCTGGCGGCGCCAAACACCCGGTATTTATTTCGCCCC...
253      DNAH17  ATGTGGCAGTTGGAGCCCCTCGAGGGAAGGGAGCCATTTTCTTTCC...
254       ASXL3  AGGCACTAGAAAAACACCCCAACTCACCAATGACAGCAAAGCAGAT...
255       CRLS1  AGTATGGAGGCAGCGGTAGCCCAGTGTCTGAGTGGTTGCCGGGTCT...
256      DYRK1A  GGCATTTTCCGGCTAGGAGGCCCGCCAGCCCTTCGAAGAACCGGCT...

[257 rows x 2 columns]

In [19]:
df_secs.to_csv('datosGene4PD/secuencias_genes.csv', index = False)