In [1]:
# pip install mygene

In [1]:
import pandas as pd
import numpy as np
import requests
import time
import mygene

In [2]:
df = pd.read_csv("datosGene4PD/t_common_variant.txt", sep = "\t", index_col = False)

In [3]:
df.head()

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID,Unnamed: 10
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260,NaN
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889,NaN
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889,NaN
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889,NaN
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889,NaN

In [4]:
df_genes = df["gene_symbol"]

In [5]:
df_genes

0        GPR126
1         SYT11
2       SLC2A13
3       SLC2A13
4       SLC2A13
         ...
1053     INPP5F
1054       RIT2
1055       GCH1
1056    SIPA1L2
1057    TMPRSS9
Name: gene_symbol, Length: 1058, dtype: object

In [6]:
df_genes_t = df_genes.dropna()

In [7]:
df_genes_t = df_genes_t.reset_index(drop=False)["gene_symbol"]

In [8]:
df_genes_t

0        GPR126
1         SYT11
2       SLC2A13
3       SLC2A13
4       SLC2A13
         ...
1051     INPP5F
1052       RIT2
1053       GCH1
1054    SIPA1L2
1055    TMPRSS9
Name: gene_symbol, Length: 1056, dtype: object

In [9]:
df_genes_t.head(20)

0              GPR126
1               SYT11
2             SLC2A13
3             SLC2A13
4             SLC2A13
5             SLC2A15
6     LINC02471;LRRK2
7               LRRK2
8               LRRK2
9         GPRIN3;SNCA
10               MAPT
11    LINC02210-CRHR1
12        GPRIN3;SNCA
13    LINC02210-CRHR1
14           SERPINA1
15           SERPINA1
16        S1PR1;OLFM3
17               MAPT
18               MAPT
19             SPPL2C
Name: gene_symbol, dtype: object

In [10]:
def extrae_gene_symbols(dataframe):

    df_corregido = df.drop('Unnamed: 10', axis = 1)
    df_corregido = df_corregido.dropna(subset = ['gene_symbol'])
    df_corregido = df_corregido.reset_index(drop=False)
    df_corregido = df_corregido.drop('index', axis = 1)
    df_genes = df_corregido["gene_symbol"]
    
    lista_symbols = []
    
    for i, gene in enumerate(df_genes):
        
        gene = gene.replace(",", ";")
    
        if "dist" in gene:
            continue

        elif ";" in gene:

            separacion1 = gene.split(";")

            for gen in separacion1:
                lista_symbols.append(gen)

        else:
            lista_symbols.append(gene)
            
    return df_corregido, lista_symbols

In [11]:
df_corregido, lista_symbols = extrae_gene_symbols(df)

In [12]:
# for gen in lista_symbols:
#     print(gen)

In [12]:
mg = mygene.MyGeneInfo()

In [13]:
gen = ["GPR126"]
resultado_prueba = mg.querymany(gen, scopes = "symbol,alias", fields = "genomic_pos_hg19", species = "human")

In [14]:
print(resultado_prueba)

[{'query': 'GPR126', '_id': '57211', '_score': 18.994669, 'genomic_pos_hg19': {'chr': '6', 'end': 142767403, 'start': 142622991, 'strand': 1}}]

In [15]:
lista_unicos = []
for symbol in lista_symbols:
    if symbol not in lista_unicos:
        lista_unicos.append(symbol)

In [16]:
resultados_coords = mg.querymany(lista_unicos, scopes = "symbol,alias", fields = "genomic_pos_hg19", species = "human")

43 input query terms found dup hits:	[('TBC1D3P2', 2), ('CAST', 4), ('DHFRP3', 2), ('HLA-DQB1', 2), ('BST1', 2), ('CASC6', 2), ('PWRN4',
48 input query terms found no hit:	['SLC2A15', 'NONE', 'LOC440311', '43160', 'LOC100133091', 'LOC101928978', 'MIR7641-2', 'LOC201175',

In [24]:
# print(resultados_coords)

In [17]:
coords_genes = []
no_encontrados = []

for resultado in resultados_coords:
    
    gen = resultado.get("query")

    if resultado.get("notfound"):
        no_encontrados.append(gen)
        continue

    posicion = resultado.get("genomic_pos_hg19")
    
    if isinstance(posicion, list):
        posicion = posicion[0]

    if posicion:
        coords_genes.append({"gene_symbol": gen, "chr": str(posicion.get("chr")), "inicio": posicion.get("start"), "fin": posicion.get("end"), "cadena": posicion.get("strand")})

In [36]:
# no_encontrados

In [38]:
# coords_genes

In [18]:
df_coords = pd.DataFrame(coords_genes)

In [19]:
df_coords

    gene_symbol chr     inicio        fin  cadena
0        GPR126   6  142622991  142767403       1
1         SYT11   1  155829300  155854990       1
2       SLC2A13  12   40148823   40499891      -1
3         LRRK2  12   40590546   40763087       1
4        GPRIN3   4   90157537   90229161      -1
..          ...  ..        ...        ...     ...
594      DNAH17  17   76419778   76573476      -1
595       ASXL3  18   31158579   31331156       1
596       MEX3C  18   48700920   48744674      -1
597       CRLS1  20    5986736    6020699       1
598      DYRK1A  21   38738092   38889753       1

[599 rows x 5 columns]

In [61]:
# df['Unnamed: 10'].isna().all()

True

In [20]:
df_corregido

,Chr,gene_symbol,SNPs_symbol,SNP_position,effect_allele,alternate_allele,joint_phase_P,joint_phase_OR,joint_phase_OR_CI,pubMed_ID
0,6,GPR126,rs757765789,142758601,T,G,1.42E-06,1.06,1.016-1.098,28256260
1,1,SYT11,rs202015799,155839054,C,T,4.70E-09,-,-,24842889
2,12,SLC2A13,rs1994090,40428561,G,T,3.20E-54,12.05,8.35-17.41,24842889
3,12,SLC2A13,rs2708453,40478652,G,T,3.62E-54,12.05,8.35-17.41,24842889
4,12,SLC2A13,rs4768212,40474147,C,T,3.62E-54,12.05,8.35-17.41,24842889
...,...,...,...,...,...,...,...,...,...,...
1051,rs117896735,INPP5F,13,U,13,U,1.21E-11,1.77,-,29700661
1052,rs12456492,RIT2,21,U,21,U,2.15E-11,1.1,-,29700661
1053,rs7155501,GCH1,15,U,15,U,1.25E-10,1.12,-,29700661
1054,rs10797576,SIPA1L2,21,U,21,U,1.76E-10,1.13,-,29700661
1055,rs62120679,TMPRSS9,13,U,13,U,2.52E-09,1.14,-,29700661

In [21]:
df_SNPs = df_corregido[["Chr", "gene_symbol", "SNP_position", "effect_allele", "alternate_allele"]]

In [22]:
df_SNPs

              Chr gene_symbol SNP_position effect_allele alternate_allele
0               6      GPR126    142758601             T                G
1               1       SYT11    155839054             C                T
2              12     SLC2A13     40428561             G                T
3              12     SLC2A13     40478652             G                T
4              12     SLC2A13     40474147             C                T
...           ...         ...          ...           ...              ...
1051  rs117896735      INPP5F            U            13                U
1052   rs12456492        RIT2            U            21                U
1053    rs7155501        GCH1            U            15                U
1054   rs10797576     SIPA1L2            U            21                U
1055   rs62120679     TMPRSS9            U            13                U

[1056 rows x 5 columns]

In [23]:
df_SNPs = df_SNPs[~df_SNPs['Chr'].str.contains('rs', na = False)]

In [24]:
df_SNPs

     Chr gene_symbol SNP_position effect_allele alternate_allele
0      6      GPR126    142758601             T                G
1      1       SYT11    155839054             C                T
2     12     SLC2A13     40428561             G                T
3     12     SLC2A13     40478652             G                T
4     12     SLC2A13     40474147             C                T
...   ..         ...          ...           ...              ...
1039  17      DNAH17     76425480             A                T
1040  18       ASXL3     31304318             T                G
1041  18       MEX3C     48683589             T                G
1042  20       CRLS1      6006041             T                C
1043  21      DYRK1A     38852361             A                G

[1044 rows x 5 columns]

In [32]:
for i in range(len(df_SNPs)):
    if 
    loc_genes = {df_SNPs.iloc[i]['gene_symbol']: {'Chr': df_SNPs.iloc[i]['Chr'], 'SNP_pos': df_SNPs.iloc[i]['SNP_position']}}
    break

In [33]:
loc_genes

{'GPR126': {'Chr': '6', 'SNP_pos': '142758601'}}

In [44]:
dicc = {}
for gen in lista_unicos:
    dicc.update({gen: {'Chr':0, 'Inicio':0, 'SNPs': [], 'Fin':0, 'Cadena':0}})

In [57]:
for i in range(len(df_SNPs)):
    
    gen = df_SNPs.iloc[i]['gene_symbol']
    
    if lista_symbols.count(gen) == 1:
        
        dicc[gen]['Chr'] = df_SNPs.iloc[i]['Chr']
        dicc[gen]['SNPs'] = df_SNPs.iloc[i]['SNP_position']
        
    elif lista_symbols.count(gen) > 1:
        if len(dicc[gen]['SNPs']) == 0:
            
            dicc[gen]['Chr'] = df_SNPs.iloc[i]['Chr']
            dicc[gen]['SNPs'].append(df_SNPs.iloc[i]['SNP_position'])

        else:
            dicc[gen]['SNPs'].append(df_SNPs.iloc[i]['SNP_position'])
    else:
        continue

In [61]:
lista_symbols.count('SLC2A13')

14

In [60]:
dicc

{'GPR126': {'Chr': '6',
  'Inicio': 0,
  'SNPs': '142758601',
  'Fin': 0,
  'Cadena': 0},
 'SYT11': {'Chr': 1,
  'Inicio': 0,
  'SNPs': [155839054, 154105678, '155839054', '154105678'],
  'Fin': 0,
  'Cadena': 0},
 'SLC2A13': {'Chr': 12,
  'Inicio': 0,
  'SNPs': [40428561,
   40478652,
   40474147,
   40428561,
   40458384,
   40465786,
   40428561,
   40465942,
   40478652,
   40474147,
   '40428561',
   '40478652',
   '40474147',
   '40428561',
   '40458384',
   '40465786',
   '40428561',
   '40465942',
   '40478652',
   '40474147',
   '40442892',
   '40385118',
   '40493416'],
  'Fin': 0,
  'Cadena': 0},
 'SLC2A15': {'Chr': '14',
  'Inicio': 0,
  'SNPs': '40465942',
  'Fin': 0,
  'Cadena': 0},
 'LINC02471': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'LRRK2': {'Chr': 12,
  'Inicio': 0,
  'SNPs': [40620808,
   40734202,
   40734202,
   40757328,
   38907075,
   40614434,
   40653510,
   38907075,
   40580440,
   40632099,
   38917875,
   38907082,
   '40620808',
   '40734202',
   '40734202',
   '40757328',
   '38907075',
   '40614434',
   '40653510',
   '38907075',
   '40580440',
   '40632099',
   '38917875',
   '38907082',
   '38877384',
   '40725928',
   '40702911',
   '40650351',
   '40714009',
   '40650502'],
  'Fin': 0,
  'Cadena': 0},
 'GPRIN3': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'SNCA': {'Chr': 4,
  'Inicio': 0,
  'SNPs': [90678541,
   90675238,
   90626111,
   90709741,
   90666041,
   90668614,
   90674431,
   90646886,
   90897564,
   90639515,
   90897564,
   90711770,
   90675238,
   90675238,
   90639515,
   90756550,
   90675238,
   90645674,
   90664794,
   90657491,
   90684278,
   90655003,
   90709741,
   90734535,
   90643144,
   90709741,
   90734535,
   90757505,
   90603419,
   90757309,
   90742815,
   90729602,
   90897564,
   90688120,
   90682327,
   90696827,
   90691537,
   90692468,
   90750326,
   90707947,
   90771943,
   90705364,
   90731709,
   90665256,
   '90678541',
   '90675238',
   '90626111',
   '90709741',
   '90666041',
   '90668614',
   '90674431',
   '90646886',
   '90897564',
   '90639515',
   '90897564',
   '90711770',
   '90675238',
   '90675238',
   '90639515',
   '90756550',
   '90675238',
   '90645674',
   '90664794',
   '90657491',
   '90684278',
   '90655003',
   '90709741',
   '90734535',
   '90643144',
   '90709741',
   '90734535',
   '90757505',
   '90603419',
   '90757309',
   '90742815',
   '90729602',
   '90897564',
   '90688120',
   '90682327',
   '90696827',
   '90691537',
   '90692468',
   '90750326',
   '90707947',
   '90771943',
   '90705364',
   '90731709',
   '90665256',
   '90687507',
   '90734535',
   '90752582',
   '90713064',
   '90897564',
   '90757505',
   '90678798',
   '90657491'],
  'Fin': 0,
  'Cadena': 0},
 'MAPT': {'Chr': 18,
  'Inicio': 0,
  'SNPs': [44081064,
   44081064,
   43991272,
   44056767,
   44081064,
   43991272,
   44056767,
   44081064,
   43994648,
   43991272,
   44056767,
   43991272,
   43998822,
   44056767,
   44051846,
   44011825,
   43977827,
   44081064,
   44250108,
   43719143,
   44081064,
   44083402,
   44056767,
   44081064,
   44083948,
   '44081064',
   '44081064',
   '43991272',
   '44056767',
   '44081064',
   '43991272',
   '44056767',
   '44081064',
   '43994648',
   '43991272',
   '44056767',
   '43991272',
   '43998822',
   '44056767',
   '44051846',
   '44011825',
   '43977827',
   '44081064',
   '44250108',
   '43719143',
   '44081064',
   '44083402',
   '44056767',
   '44081064',
   '44083948',
   '44105395',
   '44071851',
   '44054696',
   '44008101',
   '44073973',
   '44102604',
   '44061278',
   '-',
   '44068924',
   '44015816',
   '44104509',
   '44101563',
   '44039691',
   '44103826',
   '44008101',
   '44073889',
   '44071851'],
  'Fin': 0,
  'Cadena': 0},
 'LINC02210-CRHR1': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [43767773,
   43728376,
   43728376,
   43767773,
   43781747,
   43751913,
   43767773,
   43767773,
   43728376,
   43728376,
   43783340,
   43812897,
   43751913,
   '43767773',
   '43728376',
   '43728376',
   '43767773',
   '43781747',
   '43751913',
   '43767773',
   '43767773',
   '43728376',
   '43728376',
   '43783340',
   '43812897',
   '43751913',
   '43811260',
   '43805194'],
  'Fin': 0,
  'Cadena': 0},
 'SERPINA1': {'Chr': 14,
  'Inicio': 0,
  'SNPs': [94845944, 94847262, '94845944', '94847262'],
  'Fin': 0,
  'Cadena': 0},
 'S1PR1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'OLFM3': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'SPPL2C': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [43923683,
   43924130,
   43923683,
   43923683,
   43924130,
   43924130,
   43923683,
   43924130,
   '43923683',
   '43924130',
   '43923683',
   '43923683',
   '43924130',
   '43924130',
   '43923683',
   '43924130',
   '43923180'],
  'Fin': 0,
  'Cadena': 0},
 'HLA-DRA': {'Chr': 6,
  'Inicio': 0,
  'SNPs': [32409530, 32409529, '32409530', '32409529'],
  'Fin': 0,
  'Cadena': 0},
 'DGKQ': {'Chr': 4,
  'Inicio': 0,
  'SNPs': [964359,
   964359,
   954359,
   955779,
   954359,
   '964359',
   '964359',
   '954359',
   '955779',
   '954359',
   '954359'],
  'Fin': 0,
  'Cadena': 0},
 'NSF': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [44788310,
   44828931,
   42145386,
   44828931,
   44790203,
   44788310,
   44788310,
   44800046,
   44800046,
   44828931,
   '44788310',
   '44828931',
   '42145386',
   '44828931',
   '44790203',
   '44788310',
   '44788310',
   '44800046',
   '44800046',
   '44828931'],
  'Fin': 0,
  'Cadena': 0},
 'PRRG4': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'QSER1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'GAK': {'Chr': 4,
  'Inicio': 0,
  'SNPs': [852313,
   852313,
   848332,
   911311,
   842313,
   878937,
   '852313',
   '852313',
   '848332',
   '911311',
   '842313',
   '878937',
   '915149',
   '865887',
   '884255'],
  'Fin': 0,
  'Cadena': 0},
 'WNT3': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [44859144,
   44865603,
   44859144,
   44865439,
   '44859144',
   '44865603',
   '44859144',
   '44865439'],
  'Fin': 0,
  'Cadena': 0},
 'CSMD1': {'Chr': 8,
  'Inicio': 0,
  'SNPs': [4277990, 3833181, '4277990', '3833181'],
  'Fin': 0,
  'Cadena': 0},
 'TAS2R19': {'Chr': '12',
  'Inicio': 0,
  'SNPs': '11174795',
  'Fin': 0,
  'Cadena': 0},
 'UNC13B': {'Chr': '9',
  'Inicio': 0,
  'SNPs': '35269819',
  'Fin': 0,
  'Cadena': 0},
 'LINC00693': {'Chr': 3,
  'Inicio': 0,
  'SNPs': [28705764, 28690589, '28705764', '28690589', '28705690'],
  'Fin': 0,
  'Cadena': 0},
 'MPHOSPH10': {'Chr': '2',
  'Inicio': 0,
  'SNPs': '71361156',
  'Fin': 0,
  'Cadena': 0},
 'ZNF519': {'Chr': '18',
  'Inicio': 0,
  'SNPs': '14105770',
  'Fin': 0,
  'Cadena': 0},
 'AAK1': {'Chr': '2', 'Inicio': 0, 'SNPs': '69723710', 'Fin': 0, 'Cadena': 0},
 'DHRS2': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'DHRS4-AS1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'C12orf75': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'CASC18': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'CDH6': {'Chr': 5,
  'Inicio': 0,
  'SNPs': [31235230, 31237336, '31235230', '31237336'],
  'Fin': 0,
  'Cadena': 0},
 'GRB10': {'Chr': '7', 'Inicio': 0, 'SNPs': '50785448', 'Fin': 0, 'Cadena': 0},
 'PIK3CD': {'Chr': '1', 'Inicio': 0, 'SNPs': '9750457', 'Fin': 0, 'Cadena': 0},
 'LY75-CD302': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'PLA2R1': {'Chr': 2,
  'Inicio': 0,
  'SNPs': [160809223,
   160815093,
   160800628,
   '160809223',
   '160815093',
   '160800628'],
  'Fin': 0,
  'Cadena': 0},
 'SH3GL2': {'Chr': 9,
  'Inicio': 0,
  'SNPs': [17608784, 17579690, '17608784', '17579690'],
  'Fin': 0,
  'Cadena': 0},
 'MED13': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [60136168, '60136168'],
  'Fin': 0,
  'Cadena': 0},
 'TBC1D3P2': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'CAST': {'Chr': 5,
  'Inicio': 0,
  'SNPs': [96078702, 96060738, 96044914, '96078702', '96060738', '96044914'],
  'Fin': 0,
  'Cadena': 0},
 'LINC01815': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'DHFRP3': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'SLCO3A1': {'Chr': '15',
  'Inicio': 0,
  'SNPs': '92562627',
  'Fin': 0,
  'Cadena': 0},
 'DNAH11': {'Chr': '7',
  'Inicio': 0,
  'SNPs': '21728627',
  'Fin': 0,
  'Cadena': 0},
 'PLEKHM1': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [43513441, 43513441, 43513441, '43513441', '43513441', '43513441'],
  'Fin': 0,
  'Cadena': 0},
 'LINC01271': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'PTPN1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'PCAT5': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'ANKRD30A': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'GABRB3': {'Chr': 15,
  'Inicio': 0,
  'SNPs': [27008264, '27008264', '26840998'],
  'Fin': 0,
  'Cadena': 0},
 'RNF130': {'Chr': '5',
  'Inicio': 0,
  'SNPs': '179400847',
  'Fin': 0,
  'Cadena': 0},
 'NONE': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'FSCB': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'MCTP2': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'LOC440311': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'DPY19L3': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'PDCD5': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'C20orf78': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'SLC24A3': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'HLA-DQB1': {'Chr': 6,
  'Inicio': 0,
  'SNPs': [32666660, '32666660'],
  'Fin': 0,
  'Cadena': 0},
 'HLA-DQA2': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'SLC22A3': {'Chr': '6',
  'Inicio': 0,
  'SNPs': '160807432',
  'Fin': 0,
  'Cadena': 0},
 'SVOPL': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'ATP6V0A4': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'MIR548AG2': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'LINC01718': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'RIPK2': {'Chr': '8', 'Inicio': 0, 'SNPs': '90803724', 'Fin': 0, 'Cadena': 0},
 'LINC02210': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [43719143,
   43719143,
   43714850,
   '43719143',
   '43719143',
   '43714850',
   '43714850'],
  'Fin': 0,
  'Cadena': 0},
 'KCNA1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'KCNA5': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'ANKRD36': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'POMGNT2': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'SNRK': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'TMEM2': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'ABHD17B': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 '43160': {'Chr': '1',
  'Inicio': 0,
  'SNPs': '220974218',
  'Fin': 0,
  'Cadena': 0},
 'SLC2A14': {'Chr': '13',
  'Inicio': 0,
  'SNPs': '40465942',
  'Fin': 0,
  'Cadena': 0},
 'ABCA3': {'Chr': 16,
  'Inicio': 0,
  'SNPs': [2345388, 2336394, '2345388', '2336394'],
  'Fin': 0,
  'Cadena': 0},
 'AP3B1': {'Chr': 5,
  'Inicio': 0,
  'SNPs': [77514173, 77380723, 77389213, '77514173', '77380723', '77389213'],
  'Fin': 0,
  'Cadena': 0},
 'MCL1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'ENSA': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'LAPTM4A': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'SDC1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'TMTC1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'IPO8': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'SND1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'MIR129-1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'HLX-AS1': {'Chr': '1',
  'Inicio': 0,
  'SNPs': '221011546',
  'Fin': 0,
  'Cadena': 0},
 'BST1': {'Chr': 4,
  'Inicio': 0,
  'SNPs': [15726564,
   15737101,
   15346199,
   15737937,
   15346199,
   15737937,
   15725766,
   15729534,
   '15726564',
   '15737101',
   '15346199',
   '15737937',
   '15346199',
   '15737937',
   '15725766',
   '15729534'],
  'Fin': 0,
  'Cadena': 0},
 'FER': {'Chr': 5,
  'Inicio': 0,
  'SNPs': [108107752, 108121356, '108107752', '108121356'],
  'Fin': 0,
  'Cadena': 0},
 'LOC100133091': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'DTX2P1-UPK3BP1-PMS2P11': {'Chr': 0,
  'Inicio': 0,
  'SNPs': [],
  'Fin': 0,
  'Cadena': 0},
 'PGGHG': {'Chr': 11,
  'Inicio': 0,
  'SNPs': [290233, 295343, '290233', '295343'],
  'Fin': 0,
  'Cadena': 0},
 'PRKG1': {'Chr': '10',
  'Inicio': 0,
  'SNPs': '53068604',
  'Fin': 0,
  'Cadena': 0},
 'CHN2': {'Chr': '7', 'Inicio': 0, 'SNPs': '29548324', 'Fin': 0, 'Cadena': 0},
 'SLC25A48': {'Chr': '5',
  'Inicio': 0,
  'SNPs': '135182123',
  'Fin': 0,
  'Cadena': 0},
 'SNCA-AS1': {'Chr': 4,
  'Inicio': 0,
  'SNPs': [90757840, '90757840', '90759047'],
  'Fin': 0,
  'Cadena': 0},
 'MMRN1': {'Chr': '4',
  'Inicio': 0,
  'SNPs': ['90816294'],
  'Fin': 0,
  'Cadena': 0},
 'TMEM175': {'Chr': 4,
  'Inicio': 0,
  'SNPs': [939113, 951947, 929113, '939113', '951947', '929113', '932006'],
  'Fin': 0,
  'Cadena': 0},
 'KANSL1': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [44247164,
   44222335,
   44293020,
   44293020,
   44247164,
   44247164,
   44189067,
   44189067,
   '44247164',
   '44222335',
   '44293020',
   '44293020',
   '44247164',
   '44247164',
   '44189067',
   '44189067',
   '44131305',
   '44108202',
   '44111613'],
  'Fin': 0,
  'Cadena': 0},
 'CARMIL1': {'Chr': '6',
  'Inicio': 0,
  'SNPs': '25359545',
  'Fin': 0,
  'Cadena': 0},
 'CASC6': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'EPHA7': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'GPAT3': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'LOC101928978': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'IL2RA': {'Chr': 10,
  'Inicio': 0,
  'SNPs': [6079344, 6079479, '6079344', '6079479'],
  'Fin': 0,
  'Cadena': 0},
 'LINC01572': {'Chr': '16',
  'Inicio': 0,
  'SNPs': '72527247',
  'Fin': 0,
  'Cadena': 0},
 'NDN': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'PWRN4': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'NEDD9': {'Chr': 6,
  'Inicio': 0,
  'SNPs': [11264612, 11286280, '11264612', '11286280'],
  'Fin': 0,
  'Cadena': 0},
 'RBFOX1': {'Chr': 16,
  'Inicio': 0,
  'SNPs': [6868379, 6874468, '6868379', '6874468', '6167285', '6388799'],
  'Fin': 0,
  'Cadena': 0},
 'RGS17': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'MIR7641-2': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'TMPRSS12': {'Chr': 12,
  'Inicio': 0,
  'SNPs': [51259197, '51259197'],
  'Fin': 0,
  'Cadena': 0},
 'METTL7A': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'ZNF804B': {'Chr': 7,
  'Inicio': 0,
  'SNPs': [88551456, 88554143, '88551456', '88554143'],
  'Fin': 0,
  'Cadena': 0},
 'NUPL2': {'Chr': '7', 'Inicio': 0, 'SNPs': '23240263', 'Fin': 0, 'Cadena': 0},
 'APOE': {'Chr': '19', 'Inicio': 0, 'SNPs': '45411941', 'Fin': 0, 'Cadena': 0},
 'STH': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'DPM3': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'KRTCAP2': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'MCCC1': {'Chr': 3,
  'Inicio': 0,
  'SNPs': [182762437,
   182760073,
   182743267,
   182755209,
   182799242,
   182802874,
   182800039,
   182763580,
   182778941,
   '182762437',
   '182760073',
   '182743267',
   '182755209',
   '182799242',
   '182802874',
   '182800039',
   '182763580',
   '182778941'],
  'Fin': 0,
  'Cadena': 0},
 'GBA': {'Chr': 1,
  'Inicio': 0,
  'SNPs': [153472258, 153451576, '153472258', '153451576'],
  'Fin': 0,
  'Cadena': 0},
 'STK39': {'Chr': 2,
  'Inicio': 0,
  'SNPs': [169110394,
   169091942,
   '169110394',
   '169091942',
   '169117025',
   '169117025'],
  'Fin': 0,
  'Cadena': 0},
 'ACMSD': {'Chr': '2',
  'Inicio': 0,
  'SNPs': ['135592381'],
  'Fin': 0,
  'Cadena': 0},
 'TMEM163': {'Chr': '2',
  'Inicio': 0,
  'SNPs': ['135295180'],
  'Fin': 0,
  'Cadena': 0},
 'FAM47E': {'Chr': 4,
  'Inicio': 0,
  'SNPs': [77176768,
   77176281,
   77199414,
   77192868,
   77185293,
   77193449,
   '77176768',
   '77176281',
   '77199414',
   '77192868',
   '77185293',
   '77193449',
   '77204500',
   '77176281'],
  'Fin': 0,
  'Cadena': 0},
 'FAM47E-STBD1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'CCDC62': {'Chr': 12,
  'Inicio': 0,
  'SNPs': [123303586, '123303586'],
  'Fin': 0,
  'Cadena': 0},
 'HIP1R': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'RAB7L1': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'NUCKS1': {'Chr': 1,
  'Inicio': 0,
  'SNPs': [205713378, 205713378, '205713378', '205713378'],
  'Fin': 0,
  'Cadena': 0},
 'C17orf69': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [43719143, 43719143, '43719143', '43719143'],
  'Fin': 0,
  'Cadena': 0},
 'NDUFAF2': {'Chr': '5',
  'Inicio': 0,
  'SNPs': '60273923',
  'Fin': 0,
  'Cadena': 0},
 'PARK16': {'Chr': 1,
  'Inicio': 0,
  'SNPs': [205752665,
   205752665,
   205725028,
   '205752665',
   '205752665',
   '205725028'],
  'Fin': 0,
  'Cadena': 0},
 'CRHR1': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [43912454,
   43912723,
   43912830,
   43912582,
   43912635,
   '43912454',
   '43912723',
   '43912830',
   '43912582',
   '43912635'],
  'Fin': 0,
  'Cadena': 0},
 'TMEM229B': {'Chr': 14,
  'Inicio': 0,
  'SNPs': [67984370, '67984370'],
  'Fin': 0,
  'Cadena': 0},
 'GPNMB': {'Chr': 7,
  'Inicio': 0,
  'SNPs': [23306020, 23293746, '23306020', '23293746', '23306020'],
  'Fin': 0,
  'Cadena': 0},
 'INPP5F': {'Chr': 10,
  'Inicio': 0,
  'SNPs': [121536327, '121536327'],
  'Fin': 0,
  'Cadena': 0},
 'KIAA1267': {'Chr': '17',
  'Inicio': 0,
  'SNPs': '44250108',
  'Fin': 0,
  'Cadena': 0},
 'SETD1A': {'Chr': '16',
  'Inicio': 0,
  'SNPs': '30982225',
  'Fin': 0,
  'Cadena': 0},
 'MAPT-AS1': {'Chr': 17,
  'Inicio': 0,
  'SNPs': [43925297, 43925297, '43925297', '43925297', '43970662', '43970154'],
  'Fin': 0,
  'Cadena': 0},
 'ZNF184': {'Chr': '6',
  'Inicio': 0,
  'SNPs': '27681215',
  'Fin': 0,
  'Cadena': 0},
 'SLC41A1': {'Chr': 1,
  'Inicio': 0,
  'SNPs': [205764640,
   205764640,
   205777780,
   205764640,
   205777780,
   '205764640',
   '205764640',
   '205777780',
   '205764640',
   '205777780',
   '205771173',
   '205764640',
   '205777780'],
  'Fin': 0,
  'Cadena': 0},
 'RAB25': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'BCKDK': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'STX1B': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'CTSB': {'Chr': '8', 'Inicio': 0, 'SNPs': '11707174', 'Fin': 0, 'Cadena': 0},
 'RIT2': {'Chr': 18,
  'Inicio': 0,
  'SNPs': [40673380,
   40678235,
   '40673380',
   '40678235',
   '40672418',
   '40681293',
   '40554893',
   '40601298',
   '40565905'],
  'Fin': 0,
  'Cadena': 0},
 'MIR4697': {'Chr': 11,
  'Inicio': 0,
  'SNPs': [133765367, '133765367'],
  'Fin': 0,
  'Cadena': 0},
 'RORA': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'LINC02349': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'ITPKB': {'Chr': '1',
  'Inicio': 0,
  'SNPs': '226916078',
  'Fin': 0,
  'Cadena': 0},
 'FGF20': {'Chr': 8,
  'Inicio': 0,
  'SNPs': [16697091, 16697091, '16697091', '16697091'],
  'Fin': 0,
  'Cadena': 0},
 'DDRGK1': {'Chr': '20',
  'Inicio': 0,
  'SNPs': '3168166',
  'Fin': 0,
  'Cadena': 0},
 'ANK2': {'Chr': '4',
  'Inicio': 0,
  'SNPs': ['113887737'],
  'Fin': 0,
  'Cadena': 0},
 'CAMK2D': {'Chr': 0, 'Inicio': 0, 'SNPs': [], 'Fin': 0, 'Cadena': 0},
 'MAP4K4': {'Chr': '2',
  'Inicio': 0,
  'SNPs': '102413116',
  'Fin': 0,
  'Cadena': 0},
 'GCH1': {'Chr': 14,
  'Inicio': 0,
  'SNPs': [55348869, '55348869', '55373670'],
  'Fin': 0,
  'Cadena': 0},
 'LOC201175': {'Chr': '17',